include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    todo: ignore

linter:
  rules:
    lines_longer_than_80_chars: false
    depend_on_referenced_packages: true
